### PR TITLE
Fix tests broken when Suggests:ed package are missing

### PR DESCRIPTION
**Pull request by HenrikBengtsson**
Ok, with my PRs, I got it to pass:
```sh
$ _R_CHECK_FORCE_SUGGESTS_=false R CMD check *.tar.gz
```
Enough procrastination on my end - back to some admin work.

I really think you should aim at having the package pass `R CMD check --as-cran` with only OKs.  That will communicate much more confidence and trust.

### CODE REVIEW

**Comment by egenn** [comment]
> Ok, with my PRs, I got it to pass:
> 
> ```shell
> $ _R_CHECK_FORCE_SUGGESTS_=false R CMD check *.tar.gz
> ```
> 
> Enough procrastination on my end - back to some admin work.
> 
> I really think you should aim at having the package pass `R CMD check --as-cran` with only OKs. That will communicate much more confidence and trust.

Thanks, Henrik. I added a test around each command. It's back to a single warning for the unfinished documentation, which is getting there.

**Comment by HenrikBengtsson** [comment]
That's awesome news ...

However, are testing with `R CMD check`, or similarly, with `devtools::check()`, because I get:
```r
── Install failure ──────────────────────────────────

* installing *source* package 'rtemis' ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(name) : there is no package called 'R6'
Error : unable to load R code in package 'rtemis'
ERROR: lazy loading failed for package 'rtemis'
* removing '/tmp/RtmpKh22Ql/rtemis.Rcheck/rtemis'

2 errors ✖ | 0 warnings ✔ | 1 note ✖
```

Looking at the code, you have lots of R6 dependencies at the top-level of your package code, which means R6 must be in either Imports or Suggests;

```sh
$ grep -F "R6::" -r --include="*.R" | head -5
R/rtMod.R:rtMod <- R6::R6Class("rtMod",
R/rtMod.R:rtModClass <- R6::R6Class("rtModClass",
R/rtMod.R:rtModBag <- R6::R6Class("rtModBag",
R/rtMod.R:rtModCV <- R6::R6Class("rtModCV",
R/rtMod.R:rtModCVclass <- R6::R6Class("rtModCVclass",
```

I recommend setting up Travis CI so you're not biased by your local setup.

**Comment by egenn** [comment]
I don't know why you got that - R6 was already in Suggests. I moved it to Imports (though on second thought it may have been best left in Suggests)

I am using devtools::check() and/or R CMD check after every nontrivial code change. 

Travis fails with the non-CRAN packages. (Note that .travis.yml includes `warnings_are_errors: false`)

`Error: (converted from warning) packages ‘ANTsR’, ‘gbm3’, ‘hopach’, ‘impute’, ‘mxnet’, ‘sgd’ are not available (for R version 3.5.3)
Execution halted
The command "Rscript -e 'deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .`

What's the preferred way to solve this?
I  can add the GitHub and Bioconductor packages to Remotes in DESCRIPTION - if that's the right thing to do - but mxnet and h2o can't be installed without their respective system libraries. How should they be bypassed in Travis?

**Comment by egenn** [comment]
(Adding a long `before_install` section in .travis.yml for mxnet and h2o would be entirely unrealistic in terms of time and further dependencies)

**Comment by HenrikBengtsson** [comment]
Whoops, I meant Imports or **Depends**. I got the error on the master branch.

For Travis: You should only have to have packages under Depends and Imports installed. Packages under Suggests should be optional (given that your code and your tests only use those conditionally).

**Comment by HenrikBengtsson** [comment]
There are settings to tell r-travis not to install packages under Suggests.

**Comment by HenrikBengtsson** [comment]
Also, if you don't get the error locally on your machine, could it be that you install R packages as admin so they end up in the library path where R has its core pkgs? Doing so will prevent R CMD check from checking the pkg properly because it will always see those pkgs.  You want to run R and install pkgs as a regular non-priv user. Just a guess.

**Comment by egenn** [comment]
No, I install all packages to a separate directory, as a regular user. Found some combination of Travis arguments that work - for now.

**Comment by HenrikBengtsson** [comment]
Good that you got something up for Travis. Now, the reason why you have to install those package deps manually in the `before_install` is a strong indicator of misconfiguration in DESCRIPTION (probably why I'm seeing what I'm seeing). This is also why the package wont install/load out of the box for people with a fresh R setup.

I recommend that you remove the installation of those deps and fix DESCRIPTION accordingly (e.g. move from Suggests to Imports) until it works.

After that, I would drop also the `install` entry because r-travis should automatically install the GitHub package being tested. When everything works correctly, you should have a travis.yml file that is very generic.

Only after this you can start optimizing which of those packages really have to be under Imports and not.

**Comment by egenn** [comment]
I finished adding conditions in /tests. and the .travis.yml is now:
`before_install:
  - R -e 'install.packages(c("remotes"))'

install:
  - R -e 'remotes::install_deps(dep = NA)'`

This was just to get `dep = NA` - If I find a better way to skip installing Suggests, I'll change it.

Eventually I definitely want it to install everything in Suggests (probably using binaries when available) so that most tests are run, but excluding those few packages with extended dependencies, like ANTsR. When I tried installing all in Suggests it was working fine but took forever and timed out:
`9952 The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by HenrikBengtsson** [comment]
> Eventually I definitely want it to install everything in Suggests (probably using binaries when available) so that most tests are run, but excluding those few packages with extended dependencies, like ANTsR. When I tried installing all in Suggests it was working fine but took forever and timed out [...]

The 50 minute timeout limit is per Travis job.  You can create multiple jobs per Travis build.  So, one solution is to create multiple jobs and only install one or a few of the Suggests:ed package per job.  I use this trick in a few of my packages where testing everything at once would take more than 50 mins.  I don't have an example of install only some of the Suggests:ed packages, but I look at the following examples to get the gist:

1. future.tests
  * https://github.com/HenrikBengtsson/future.tests/blob/master/.travis.yml
  * https://travis-ci.org/HenrikBengtsson/future.tests

2. doFuture
  * https://github.com/HenrikBengtsson/doFuture/blob/master/.travis.yml
  * https://travis-ci.org/HenrikBengtsson/doFuture

3. matrixStats
  * https://github.com/HenrikBengtsson/matrixStats/blob/master/.travis.yml
  * https://travis-ci.org/HenrikBengtsson/matrixStats

**Pull request merged**
